// Automatically generated by the bundler tool from c:\Documents and Settings\Xboxdev\Perforce\signetti_workspace_xbox5\Cohort12-Public\Classes\Programming\XBOX Games\An-si\Game\XBoxFramework\resource.rdf

#define resource_NUM_RESOURCES 6UL

#define resource_Menu_OFFSET 0UL
#define resource_Background_OFFSET 20UL
#define resource_SpriteSheet_OFFSET 40UL
#define resource_ScoreFont_OFFSET 60UL
#define resource_GameOverScreen_OFFSET 80UL
#define resource_TransitionMenu_OFFSET 100UL
